### ISSUE TITLE
NuGet package listing

### ISSUE THREAD

**Issue by alexeyzimarev** [Alterdata/RestSharp.Newtonsoft.Json.NetCore#1]
Hey,

Thank you for supporting RestSharp :) I'd like, however, to ask you to remove (unlist) your package since RestSharp supports .NET Core and also has the NewtonsoftJson serializer as a dedicated package (https://www.nuget.org/packages/RestSharp.Serializers.NewtonsoftJson) for a while now so we don't confuse users. Besides, the package that your project references has been unlisted on NuGet.

Thanks and regards,
Alexey Zimarev
Maintainer of RestSharp

**Comment by bernardbr** [comment]
Hey, @alexeyzimarev!

I deprecated the package and pointed at https://www.nuget.org/packages/RestSharp.Serializers.NewtonsoftJson as the suggested alternative.

I didn't unlist the package because it will still be used in the company for some new projects.

Regards

**Comment by alexeyzimarev** [comment]
Thanks! Really appreciate it.
